name: Cool Advertising Finds
favicon: null
layout_spectrum: 0
typography_spectrum: 0.15577
title: Cool Hunting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#979c9c'
    - '#343642'
    - '#f2ebc7'
    - '#962d3e'
    - '#348899'
  brandStrength: 0.9551223425660282
  lightness: 0.340838560834527
  saturation: 0.4773926588241011
  rhythmicContrast: 0.15221802331507206
purpose: []
